import SwiftUI
import PDFKit

@MainActor
struct PDFComposer {
    
    static func render(claim: Claim) -> URL? {
        let pdfMetaData = [
            kCGPDFContextCreator: "Stance Intelligence",
            kCGPDFContextAuthor: "Stance App",
            kCGPDFContextTitle: "Advocacy Report: \(claim.originalText)"
        ]
        
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]
        
        let pageWidth = 8.5 * 72.0
        let pageHeight = 11.0 * 72.0
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)
        
        let data = renderer.pdfData { (context) in
            context.beginPage()
            
            // Draw Header
            let titleAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 24, weight: .bold),
                .paragraphStyle: NSMutableParagraphStyle()
            ]
            let title = "Advocacy Report"
            title.draw(at: CGPoint(x: 50, y: 50), withAttributes: titleAttributes)
            
            // Draw Claim
            let claimAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 18),
                .foregroundColor: UIColor.darkGray
            ]
            claim.originalText.draw(at: CGPoint(x: 50, y: 100), withAttributes: claimAttributes)
            
            // Draw Disclaimer
            let footer = "Generated by Stance. Strictly Confidential."
            footer.draw(at: CGPoint(x: 50, y: pageHeight - 50), withAttributes: claimAttributes)
        }
        
        return save(data: data, title: "StanceReport-\(claim.id).pdf")
    }
    
    private static func save(data: Data, title: String) -> URL? {
        let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        let docDirectory = paths[0]
        let url = docDirectory.appendingPathComponent(title)
        
        do {
            try data.write(to: url)
            return url
        } catch {
            print("PDF Save Error: \(error)")
            return nil
        }
    }
}
