import SwiftUI
import PDFKit

@MainActor
struct PDFComposer {
    
    static func render(claim: Claim) -> URL? {
        let pdfMetaData = [
            kCGPDFContextCreator: "Stance Intelligence",
            kCGPDFContextAuthor: "Stance App",
            kCGPDFContextTitle: "Advocacy Report: \(claim.originalText)"
        ]
        
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]
        
        let pageWidth = 8.5 * 72.0
        let pageHeight = 11.0 * 72.0
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)
        
        let data = renderer.pdfData { (context) in
            context.beginPage()
            
            // Draw Header
            let titleAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 24, weight: .bold),
                .paragraphStyle: NSMutableParagraphStyle()
            ]
            let title = "Advocacy Report"
            title.draw(at: CGPoint(x: 50, y: 50), withAttributes: titleAttributes)
            
            // Draw Claim
            let claimAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 18),
                .foregroundColor: UIColor.darkGray
            ]
            claim.originalText.draw(at: CGPoint(x: 50, y: 100), withAttributes: claimAttributes)
            
            // Draw Evidence Summary
            let headerAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 16, weight: .bold)
            ]
            "Key Supportive Trends:".draw(at: CGPoint(x: 50, y: 150), withAttributes: headerAttributes)
            
            var yOffset: CGFloat = 180
            let bodyAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 12)
            ]
            
            for evidence in claim.evidence.prefix(5) {
                let line = "• \(evidence.description) (Confidence: \(Int(evidence.confidence * 100))%)"
                line.draw(at: CGPoint(x: 60, y: yOffset), withAttributes: bodyAttributes)
                
                // Draw Chart
                let chartRect = CGRect(x: 60, y: yOffset + 20, width: 300, height: 80)
                ChartRenderer().render(evidence: evidence, in: chartRect, context: context.cgContext)
                
                yOffset += 120 // Space for text + chart
            }
            
            // Draw Methodology
            if let method = claim.methodology {
                let methodTitle = "Methodology & Assumptions:"
                methodTitle.draw(at: CGPoint(x: 50, y: pageHeight - 120), withAttributes: headerAttributes)
                
                let methodRect = CGRect(x: 50, y: pageHeight - 100, width: pageWidth - 100, height: 40)
                let methodAttributes: [NSAttributedString.Key: Any] = [
                    .font: UIFont.italicSystemFont(ofSize: 10),
                    .foregroundColor: UIColor.gray
                ]
                method.draw(in: methodRect, withAttributes: methodAttributes)
            }
            
            // Draw Disclaimer
            let footer = "Generated by Stance. Strictly Confidential."
            footer.draw(at: CGPoint(x: 50, y: pageHeight - 50), withAttributes: claimAttributes)
        }
        
        return save(data: data, title: "StanceReport-\(claim.id).pdf")
    }
    
    private static func save(data: Data, title: String) -> URL? {
        let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        let docDirectory = paths[0]
        let url = docDirectory.appendingPathComponent(title)
        
        do {
            try data.write(to: url)
            return url
        } catch {
            print("PDF Save Error: \(error)")
            return nil
        }
    }
}
